# Generated by Django 2.2.6 on 2019-10-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_month', models.CharField(max_length=255, verbose_name='開催月')),
                ('boss_number', models.IntegerField(verbose_name='番号')),
                ('boss_name', models.CharField(max_length=255, verbose_name='ボス名')),
                ('max_hit_point', models.IntegerField(verbose_name='HP')),
                ('target', models.IntegerField(verbose_name='ダメージ目安')),
            ],
            options={
                'db_table': 'boss',
            },
        ),
    ]
