# Generated by Django 2.2.6 on 2019-10-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='target',
            field=models.CharField(max_length=255, verbose_name='ダメージ目安'),
        ),
    ]
