# Generated by Django 2.2.6 on 2019-10-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0002_auto_20191009_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザ名')),
            ],
            options={
                'db_table': 'clan_members',
            },
        ),
    ]
