# Generated by Django 2.2.6 on 2019-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0003_clanmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='予約日')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('boss_number', models.IntegerField(verbose_name='番号')),
                ('is_attack', models.BooleanField(verbose_name='凸済みか')),
            ],
            options={
                'db_table': 'boss_reserve',
            },
        ),
    ]
