# Generated by Django 2.2.6 on 2019-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0004_bossreserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_number', models.IntegerField(verbose_name='番号')),
                ('hit_point', models.IntegerField(verbose_name='残りHP')),
            ],
            options={
                'db_table': 'current_boss',
            },
        ),
    ]
