# Generated by Django 2.2.6 on 2019-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0005_currentboss'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='凸時間')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('boss_number', models.IntegerField(verbose_name='番号')),
                ('damage', models.IntegerField(verbose_name='ダメージ')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('is_carry_over', models.IntegerField(verbose_name='持ち越し')),
            ],
            options={
                'db_table': 'attack_log',
            },
        ),
    ]
