# Generated by Django 2.2.6 on 2019-10-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0006_attacklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacklog',
            old_name='datetime',
            new_name='attack_time',
        ),
    ]
