# Generated by Django 2.2.6 on 2019-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0007_auto_20191010_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carried_at', models.DateTimeField(verbose_name='処理日')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('boss_number', models.IntegerField(verbose_name='番号')),
                ('time', models.IntegerField(verbose_name='持ち越し時間')),
            ],
            options={
                'db_table': 'carry_over',
            },
        ),
        migrations.RenameField(
            model_name='bossreserve',
            old_name='datetime',
            new_name='reserved_at',
        ),
    ]
