# Generated by Django 2.2.6 on 2019-10-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0008_auto_20191010_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='event_month',
            field=models.DateField(max_length=255, verbose_name='開催月'),
        ),
    ]
