# Generated by Django 2.2.6 on 2019-10-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0009_auto_20191010_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossreserve',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='キャンセル'),
        ),
        migrations.AddField(
            model_name='carryover',
            name='is_attack',
            field=models.BooleanField(default=False, verbose_name='凸済み'),
        ),
        migrations.AlterField(
            model_name='bossreserve',
            name='is_attack',
            field=models.BooleanField(default=False, verbose_name='凸済み'),
        ),
    ]
