# Generated by Django 2.2.6 on 2019-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0010_auto_20191011_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmembers',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='正式メンバー'),
        ),
    ]
